# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:

- powershell: 
    get-childitem "Get-BusinessHoursElapsed.psm1";
    import-module .\Get-BusinessHoursElapsed.psm1;
    $FirstdDate = (get-date).AddDays(-3).ToString("yyyy-MM-dd hh:mm:ss tt");
    $SecondDate = Get-Date -Format "yyyy-MM-dd hh:mm:ss tt";
    $FirstDate;
    $SecondDate;
    $BusinessHours = "9,17"
    Get-BusinessHoursElapsed -FirstDate $FirstDate-LastDate $SecondDate -BusinessHours $BusinessHours -Verbose;
  displayName: 'Calculating Business hours'
