# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:

- powershell:
    write-host "Checking if module exists";
    get-childitem "Get-BusinessHoursElapsed.psm1";

    write-host "Importing module";
    import-module .\Get-BusinessHoursElapsed.psm1 -verbose ; 

    write-host "Setting required variables";
    $FirstDate = (get-date).AddDays(-3).ToString("yyyy-MM-dd hh:mm:ss tt");
    $SecondDate = Get-Date -Format "yyyy-MM-dd hh:mm:ss tt";
    $BusinessHours = "9,17";

    Write-Host "FirstDate = $FirstDate";
    Write-Host "SecondDate = $SecondDate;
    Write-Host "BusinessHours = $BusinessHours;

    Write-Host "Starting Business Hour calculation";
    Get-BusinessHoursElapsed -FirstDate $FirstDate -LastDate $SecondDate -BusinessHours $BusinessHours -Verbose;
  displayName: 'Testing module'
